"""create_db

Revision ID: d6c060c74ab5
Revises: 
Create Date: 2023-11-22 23:35:45.507980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c060c74ab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiresults2',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('mobile_tel', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('utm_source', sa.Text(), nullable=True),
    sa.Column('utm_campaing', sa.Text(), nullable=True),
    sa.Column('utm_medium', sa.Text(), nullable=True),
    sa.Column('utm_term', sa.Text(), nullable=True),
    sa.Column('utm_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('assigned', sa.String(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('success_date', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('income_in', sa.Integer(), nullable=True),
    sa.Column('income_out', sa.Integer(), nullable=True),
    sa.Column('bitrix_id', sa.Integer(), nullable=True),
    sa.Column('loaded_sheets', sa.Boolean(), nullable=True),
    sa.Column('in_queque', sa.Boolean(), nullable=True),
    sa.Column('avito', sa.Boolean(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cuz', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('photo_pack_link', sa.Text(), nullable=True),
    sa.Column('penalty_check', sa.Boolean(), nullable=True),
    sa.Column('penalty_status', sa.String(), nullable=True),
    sa.Column('listener1_id', sa.Integer(), nullable=True),
    sa.Column('listener2_id', sa.Integer(), nullable=True),
    sa.Column('listener1_datetime', sa.DateTime(), nullable=True),
    sa.Column('listener2_datetime', sa.DateTime(), nullable=True),
    sa.Column('tr_nomer', sa.Float(), nullable=True),
    sa.Column('tr_oper', sa.Float(), nullable=True),
    sa.Column('tr_suc', sa.Float(), nullable=True),
    sa.Column('tr_pros', sa.Float(), nullable=True),
    sa.Column('tr_ruk', sa.Float(), nullable=True),
    sa.Column('full_tr', sa.Float(), nullable=True),
    sa.Column('status_before_success', sa.String(), nullable=True),
    sa.Column('success_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_apiresults2_assigned_id'), 'apiresults2', ['assigned_id'], unique=False)
    op.create_index(op.f('ix_apiresults2_site'), 'apiresults2', ['site'], unique=False)
    op.create_index(op.f('ix_apiresults2_status'), 'apiresults2', ['status'], unique=False)
    op.create_table('comments2',
    sa.Column('answerid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('groups_cc',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('call_norm', sa.Integer(), nullable=True),
    sa.Column('price_success', sa.Float(), nullable=True),
    sa.Column('price_call', sa.Float(), nullable=True),
    sa.Column('listening', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('operator_stat_new',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_before', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('projects2',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sites', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('car_condition', sa.Text(), nullable=True),
    sa.Column('bt', sa.Boolean(), nullable=True),
    sa.Column('bitrixroute', sa.Text(), nullable=True),
    sa.Column('status_id', sa.String(), nullable=True),
    sa.Column('tg_users_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('amo', sa.Boolean(), nullable=True),
    sa.Column('income_in', sa.Integer(), nullable=True),
    sa.Column('income_out', sa.Integer(), nullable=True),
    sa.Column('sites_name', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sheets', sa.Text(), nullable=True),
    sa.Column('list', sa.Text(), nullable=True),
    sa.Column('answer_cost', sa.Integer(), nullable=True),
    sa.Column('avito', sa.Boolean(), nullable=True),
    sa.Column('bitrix_title', sa.Text(), nullable=True),
    sa.Column('numbers', sa.Boolean(), nullable=True),
    sa.Column('experiment', sa.Integer(), nullable=True),
    sa.Column('uniq', sa.Integer(), nullable=True),
    sa.Column('utm_status', sa.Text(), nullable=True),
    sa.Column('name_for_operator', sa.String(), nullable=True),
    sa.Column('managers_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('vdl', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('needed_price', sa.Float(), nullable=True),
    sa.Column('vdl_tz', sa.Text(), nullable=True),
    sa.Column('pre_final_noanswer', sa.Text(), nullable=True),
    sa.Column('pre_final_exp', sa.Text(), nullable=True),
    sa.Column('script_lvl', sa.Integer(), nullable=True),
    sa.Column('days_to_reset', sa.Integer(), nullable=True),
    sa.Column('rtc_transfer', sa.Boolean(), nullable=True),
    sa.Column('status_change_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sites2',
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('dealer', sa.Text(), nullable=True),
    sa.Column('pre_final_noanswer', sa.Text(), nullable=True),
    sa.Column('pre_final_exp', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('fio', sa.String(), nullable=True),
    sa.Column('premissions', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('projects', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sites', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('active_operator_session', sa.Boolean(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('assigned', sa.String(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('uis_login', sa.String(), nullable=True),
    sa.Column('uis_password', sa.String(), nullable=True),
    sa.Column('rtc_on', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('withdraw_types',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('withdraws',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('withdraw', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('success_stat',
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('assigned_name', sa.String(), nullable=True),
    sa.Column('datetimef', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['apiresults2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_stat')
    op.drop_table('withdraws')
    op.drop_table('withdraw_types')
    op.drop_table('users')
    op.drop_table('sites2')
    op.drop_table('projects2')
    op.drop_table('operator_stat_new')
    op.drop_table('groups_cc')
    op.drop_table('comments2')
    op.drop_index(op.f('ix_apiresults2_status'), table_name='apiresults2')
    op.drop_index(op.f('ix_apiresults2_site'), table_name='apiresults2')
    op.drop_index(op.f('ix_apiresults2_assigned_id'), table_name='apiresults2')
    op.drop_table('apiresults2')
    # ### end Alembic commands ###
